apiVersion: v1
kind: ConfigMap

metadata:
  name: store-config
  namespace: store-prod

data:

  APP_ENVIRONMENT: "production"
  APP_NAME: "DevOps Store"

  index.html: |
    <!DOCTYPE html>
    <html>

    <head>
      <title>DevOps Store</title>
    </head>

    <body>

      <h1>DevOps Store</h1>

      <h2>Kubernetes Production Deployment</h2>

      <p>
        This application is running as a highly available
        Kubernetes workload.
      </p>

    </body>

    </html>